### ISSUE TITLE
Tag and push all releases to supermarket

### ISSUE THREAD

**Issue by patcon** [lipro-cookbooks/test-helper#3]
Would be nice if it's not too much trouble, so we're not pulling from github in our berksfiles

**Comment by rexut** [comment]
Give me some time to evaluate this part of workflow. I've never release on / push to Chef supermarket. Can you give me some references to do this?

**Comment by patcon** [comment]
Hm. I've been doing it a complicated way, but you instigated me to do some research, and this seems much better (though I haven't used it):
https://github.com/sethvargo/stove

**Comment by rexut** [comment]
see: https://supermarket.chef.io/cookbooks/test-helper

**Comment by rexut** [comment]
FYI: stove was really helpful which is so easy ...

**Comment by patcon** [comment]
Yay!
