### ISSUE TITLE
[meta] deprecated if using chef_zero provisioner?

### ISSUE THREAD

**Issue by patcon** [lipro-cookbooks/test-helper#5]
This was pointed out to me just now: https://github.com/bflad/chef-stash/pull/105#issuecomment-180520770

Is it your understand that this cookbook isn't needed when using chef-zero, or is there some extenuating factor that makes this useful. Thanks for any feedback!

**Comment by rexut** [comment]
I'm unsure. The original code from http://jakshi.com/blog/2014/05/12/accessing-chef-attributes-in-serverspec-tests/ was using chef-solo. For me, it was an proper way to extract information from nodes in the same way independent from the chosen provisioner, either chef-solo or chef-zero.

**Comment by patcon** [comment]
Yep, but now one less cookbook if you use chef_zero for all your testing (which I think many people do now).

Anyhow, thought it would be worth mentioning in the README that it only applied to chef_solo, and perhaps add a pointer to where the file is if using chef_zero.

Your call though. If you're alright with the above premise, just lemme know and I'll submit a PR :)

**Comment by grahamja** [comment]
I think this cookbook is still valid, even when using chef-zero. Chef-zero dumps out the whole node object. This cookbook dumps out the attributes post deep merge. Which is what we really want, right? Or am I missing something?

**Comment by patcon** [comment]
Ah wait, so there's no easy way to load that file merged from the tests? If so, then I suppose this is still advisable to use. Is there no straightforward way to load a node object from file into a deep merged hash? Or is it that we'd prefer not to install chef libs during serverspec testing?

**Comment by grahamja** [comment]
Yes, you could read the node object that was output by chef-zero. But that contains all attributes, override, default, etc. You would end up writing something very similar to this cookbook in order to get which attributes would have survived the merge.

**Comment by patcon** [comment]
:+1:

Thanks for humouring me with this issue :)
